services:
  gateway:
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - mldataset
    volumes:
      - ./gateway:/app
    restart: always

  mldataset:
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    build:
      context: ./mldatasets
      dockerfile: Dockerfile
    volumes:
      - ./mldatasets:/app
    restart: always

  auth:
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    build:
      context: ./auth
      dockerfile: Dockerfile
    volumes:
      - ./auth:/app
    restart: always
